matrix:
  include:
  - name: Test1
    language: bash
    script: echo "push branch"

  - name: Test2
    skip_cleanup: true
    language: python
    before_install: 
    - eval "$(ssh-agent -s)"
    - openssl aes-256-cbc -K $encrypted_fe7d0d738e26_key -iv $encrypted_fe7d0d738e26_iv -in test.key.enc -out test.key -d 
    - chmod 400 test.key
    - ssh-add test.key
    - pip install -r ./docs/requirements.txt
    - python ./docs/docs.py 
